AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Cognito protected HTMX contact application
Parameters:
  gatewayStage:
    Type: String
    Description: The stage name for the API Gateway
    Default: hold
Resources:
  ContactAppGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: ContactAppGateway
      OpenApiVersion: 3.0.1
      StageName: !Ref gatewayStage
  ContactApp:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        gatewayRootEvent:
          Type: Api
          Properties:
            Method: ANY
            Path: /
            RestApiId: !Ref ContactAppGateway
        gatewayEvent:
          Type: Api
          Properties:
            Method: ANY
            Path: /{proxy+}
            RestApiId: !Ref ContactAppGateway
  ContactAppDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          ForwardedValues:
            Cookies:
              Forward: all
            QueryString: true
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          Compress: true
          TargetOriginId: ContactAppGateway
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - DomainName: !Sub '${ContactAppGateway}.execute-api.${AWS::Region}.amazonaws.com'
            Id: ContactAppGateway
            OriginPath: !Sub '/${gatewayStage}'
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2

#  ContactAppUserPool:
#    Type: AWS::Cognito::UserPool
#    Properties:
#      UserPoolName: contact-app-pool
#      Schema:
#        - Name: email
#          AttributeDataType: String
#          Mutable: true
#          Required: true
#          StringAttributeConstraints:
#            MinLength: '0'
#            MaxLength: '2048'
#      Policies:
#        PasswordPolicy:
#          MinimumLength: 8
#          RequireLowercase: true
#          RequireNumbers: true
#          RequireSymbols: true
#          RequireUppercase: true
#      AutoVerifiedAttributes:
#        - email
#  HtmxUserPoolClient:
#    Type: AWS::Cognito::UserPoolClient
#    Properties:
#      ClientName: htmx-contact-app
#      UserPoolId: !Ref ContactUserPool
#      GenerateSecret: false
Outputs:
#  UserPoolId:
#    Description: "ID of the User Pool"
#    Value: !Ref ContactUserPool
#
#  UserPoolClientId:
#    Description: "ID of the User Pool Client"
#    Value: !Ref HtmxUserPoolClient
#
  DistributionDomain:
    Description: CloudFront Distribution domain name
    Value: !GetAtt ContactAppDistribution.DomainName
