AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Cognito protected HTMX contact application
Parameters:
  gatewayStage:
    Type: String
    Description: The stage name for the API Gateway
    Default: app
  userPoolDomain:
    Type: String
    Description: The domain name for the Cognito User Pool
    Default: htmx-contact-app
Resources:
  ContactAppGateway:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: 3.0.1
      StageName: !Ref gatewayStage
  ContactApp:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        gatewayRootEvent:
          Type: Api
          Properties:
            Method: ANY
            Path: /
            RestApiId: !Ref ContactAppGateway
        gatewayEvent:
          Type: Api
          Properties:
            Method: ANY
            Path: /{proxy+}
            RestApiId: !Ref ContactAppGateway
#  ContactAppDistribution:
#    Type: AWS::CloudFront::Distribution
#    Properties:
#      DistributionConfig:
#        Enabled: true
#        PriceClass: PriceClass_100
#        DefaultCacheBehavior:
#          ForwardedValues:
#            Cookies:
#              Forward: all
#            QueryString: true
#          AllowedMethods: [ HEAD, DELETE, POST, GET, OPTIONS, PUT, PATCH ]
#          Compress: true
#          TargetOriginId: ContactAppGateway
#          ViewerProtocolPolicy: redirect-to-https
#        Origins:
#          - DomainName: !Sub '${ContactAppGateway}.execute-api.${AWS::Region}.amazonaws.com'
#            Id: ContactAppGateway
#            OriginPath: !Sub '/${gatewayStage}'
#            CustomOriginConfig:
#              HTTPPort: 80
#              HTTPSPort: 443
#              OriginProtocolPolicy: https-only
#              OriginSSLProtocols:
#                - TLSv1.2
  ContactAppUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: contact-app-pool
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
          StringAttributeConstraints:
            MinLength: '0'
            MaxLength: '2048'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      AutoVerifiedAttributes:
        - email
  HtmxUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: htmx-contact-app
      UserPoolId: !Ref ContactAppUserPool
      GenerateSecret: false
      CallbackURLs:
        - !Sub 'https://${ContactAppGateway}.execute-api.${AWS::Region}.amazonaws.com/${gatewayStage}/auth/code'
      LogoutURLs:
        - !Sub 'https://${ContactAppGateway}.execute-api.${AWS::Region}.amazonaws.com/${gatewayStage}/logout'
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - COGNITO
  HtmxUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref userPoolDomain
      UserPoolId: !Ref ContactAppUserPool
Outputs:
  UserPoolId:
    Description: ID of the User Pool
    Value: !Ref ContactAppUserPool
  UserPoolClientId:
    Description: ID of the User Pool Client
    Value: !Ref HtmxUserPoolClient
  BaseUrl:
    Description: Distribution URL
    Value: !Sub 'https://${ContactAppGateway}.execute-api.${AWS::Region}.amazonaws.com/${gatewayStage}'
  SignInUrl:
    Description: Cognito Sign In URL
    Value: !Sub 'https://${userPoolDomain}.auth.${AWS::Region}.amazoncognito.com/login?response_type=code&client_id=${HtmxUserPoolClient}&redirect_uri=https://${ContactAppGateway}.execute-api.${AWS::Region}.amazonaws.com/${gatewayStage}/auth/code'
